trigger: none

pool: Docker-VM_Pool

stages:
  - stage: Terraform_Init
    displayName: Terraform Init
    jobs:
    - job: 
      displayName: Init
      continueOnError: true
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
          backendServiceArm: 'Docker-VM-Connection'
          backendAzureRmResourceGroupName: 'rg-terraform-state'
          backendAzureRmStorageAccountName: 'bkstterraformstate'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'preprod.tfstate'