trigger: 
- main

pool: Todo_Microservice_Pool

stages:
- stage:
  displayName: Build
  jobs:
  - job:
    displayName: Terraform_Install
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.11.4'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '/BrijendraYadav-dev/Terraform_Monolythic_Infra_Code'
        backendServiceArm: 'TodoApp_Service'
        backendAzureRmOverrideSubscriptionID: 'fe4b406c-7c69-45b7-8c18-908662c0d423'
        backendAzureRmResourceGroupName: 'Brijendra-RG'
        backendAzureRmStorageAccountName: 'brijendrastorgaelab'
        backendAzureRmContainerName: 'brijendracontainerlab'
        backendAzureRmKey: 'terraformstatefile'

